#include"decl.hpp"
#include"Convolute123FromZeroTo4.hpp"
#include"FastFermionicConvolute123FromZeroTo4.hpp"
#include"VeryFastFermionicConvolute123FromZeroTo4.hpp"
#include"VeryFastFermionicConvolute123FromZeroTo4Dflt.hpp"
